config/routes.rb
Rails.application.routes.draw do
devise_for :users
devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :friends
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get 'about', to: 'home#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class: "form-control" %>
  </div>

  <div>
    <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
  </div>
   <br>
  <div>
    <%= form.submit "Create Friend", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends List</h1>

<% if user_signed_in? %>
<center>   
    <%= link_to "Add new friend", new_friend_path, class: "btn btn-primary" %>
</center>
<% end %>
<br>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  
  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user_id == current_user.id %>
        <tr>
          <td><%= friend.first_name%></td>
          <td><%= friend.last_name%></td>
          <td><%= friend.phone%></td>
          <td><%= friend.twitter%></td>
          <td>
          <%= link_to "Show", friend, class: "btn btn-primary" %>    
            <%= link_to "Edit", edit_friend_path(friend), class: "btn btn-warning" %> <%= button_to "Destroy", friend, method: :delete, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card text-center">
  <div class="card-header">
    <h5 class="card-title"><%= @friend.first_name%> <%= @friend.last_name%> </h5>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @friend.email%></p>
    <p class="card-text"><%= @friend.phone%></p>
    <p class="card-text"><%= @friend.twitter%></p>
    <% if user_signed_in? %>
      <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-secondary" %> |
    <% end %>
    <%= link_to "Back to friends", friends_path, class: "btn btn-dark" %>
    <br><br>
    <% if user_signed_in? %>
      <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
   FriendsApp
  </div>
</div>

app/views/home/about.html.erb
<h1>About us...</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "FriendsApp", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "About Us", about_path, class:"nav-link" %>
            </li>
            <li class="nav-item"> 
                <%= link_to "Friends", friends_path, class:"nav-link" %>
            </li>
            

            <% if user_signed_in? %>
            
                <li class="nav-item">
                    <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
                </li>

            <% else %>

                <li class="nav-item">
                    <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                </li>

            <% end %>
            

        </ul> 

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>